idf_component_register(SRCS "main.c"
                            "board_display.c"
                            "lvgl_port.c"
                            "metrics_model.c"
                            "metrics_parser.c"
                            "metrics_io.c"
                            "ui_watch.c"
                            "fonts/lv_font_montserrat_bold_12.c"
                            "fonts/lv_font_montserrat_bold_48.c"
                            "fonts/lv_font_fan_16.c"
                       INCLUDE_DIRS "."
                       REQUIRES esp_driver_gpio esp_driver_spi esp_lcd esp_lcd_gc9a01 esp_timer lvgl)
